[package]
name = "bugi-pdk-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
# macro
proc-macro2.workspace = true
syn.workspace = true
quote.workspace = true

bugi-macro.workspace = true

[lib]
proc-macro = true
