[package]
name = "bugi_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
rand.workspace = true

serde.workspace = true
rmp-serde.workspace = true
rmpv.workspace = true

wasmtime = { version = "25.0.0" }
