[package]
name = "bugi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
rand.workspace = true

serde.workspace = true
rmp-serde.workspace = true

wasmtime = { version = "24.0.0" }
