[package]
name = "simple-pdk"
version = "0.1.0"
edition = "2021"

[dependencies]
# Seliarize
serde.workspace = true

bugi-pdk.workspace = true

[[example]]
name = "simple-pdk"
path = "src/plug.rs"
crate-type = ["cdylib"]